feat: doing home screen
ngxhuyhoang/store pull request #1
Opened 2021-12-21 10:40 UTC by Conlilo

2021-12-23 08:21 UTC, ngxhuyhoang commented on src/screens/home.tsx
> +  const get = async () => {
```suggestion
  const getProductAsync = async () => {
```

2021-12-23 08:21 UTC, ngxhuyhoang commented on src/screens/home.tsx
> +  const [dataProduct, getDataProduct] = useState([]);
```suggestion
  const [products, setProducts] = useState([]);
```

2021-12-23 08:23 UTC, ngxhuyhoang commented on src/screens/home.tsx
> +  };
Mấy cái này gom vào 1 được này

2021-12-23 08:25 UTC, ngxhuyhoang commented on src/screens/home.tsx
> +      <View style={{ flexDirection: 'row', marginLeft: 10 }}>
Đừng để inline-style

2021-12-23 08:29 UTC, ngxhuyhoang commented on src/screens/login.tsx
> +    console.log(res.data);
Ông hạn chế để console log thôi, nó cũng gây giảm hiệu năng đấy vì đoạn code này không cần nhưng nó vẫn phải compile

2021-12-23 08:40 UTC, datduong56 requested changes

2021-12-23 08:40 UTC, datduong56 commented on src/navigators/app-stack.tsx
> +      <Stack.Screen name="Product Details" component={ProductDetails} />
```suggestion
      <Stack.Screen name="ProductDetails" component={ProductDetails} />
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/home.tsx
> +  };
```suggestion
  const renderItem = ({ item }) => {
    return <Item name={item.title} img={item.image} price={item.price} />;
  };
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/home.tsx
> +          renderItem={renderMenClothing}
```suggestion
          renderItem={renderItem}
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/home.tsx
> +          renderItem={renderWomenClothing}
```suggestion
          renderItem={renderItem}
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/home.tsx
> +          renderItem={renderAcessories}
```suggestion
          renderItem={renderItem}
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/home.tsx
> +          renderItem={renderElectronic}
```suggestion
          renderItem={renderItem}
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/home.tsx
> +        onPress={() => navigation.navigate('Product Details')}>
```suggestion
        onPress={() => navigation.navigate('ProductDetails')}>
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/home.tsx
> +      <View style={{ flexDirection: 'row', marginLeft: 10 }}>
use styled component or styles instead of inline style

2021-12-23 08:40 UTC, datduong56 commented on src/screens/home.tsx
> +      <View style={{ flexDirection: 'row', marginLeft: 10 }}>
use styled component or styles instead of inline style

2021-12-23 08:40 UTC, datduong56 commented on src/screens/login.tsx
> +    console.log(res.data);
remove console.log

2021-12-23 08:40 UTC, datduong56 commented on src/screens/login.tsx
> +    (login: { username: string; password: string }) => {
```suggestion
    (login: { username: string; password: string, email: string }) => {
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/login.tsx
> +  const Verification = condition => {
```suggestion
  const handleVerification = condition => {
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/login.tsx
> +    }
```suggestion
    if (username === '' || password === '') {
      Alert.alert(
        'Username and Password can not be empty',
        'Please try again',
        [{ text: 'Congfirm', onPress: () => console.log('confirm pressed') }]
      );
      return;
    }
    if (condition.length !== 1) {
      console.log('login fail');
      createAlertLogin();
      return;
    }
    console.log('success');
     navigation.navigate('Home');
```

2021-12-23 08:40 UTC, datduong56 commented on src/screens/login.tsx
> +          <Text style={{ alignItems: 'center', marginLeft: 10 }}>Google</Text>
use styled component or styles instead of inline style

2021-12-23 08:40 UTC, datduong56 commented on src/screens/login.tsx
> +          <Text style={{ alignItems: 'center', marginTop: 20 }}>LOGIN</Text>
use styled component or styles instead of inline style

2021-12-23 08:40 UTC, datduong56 commented on src/screens/login.tsx
> +          onPress={() => Verification(accountVerification)}>
```suggestion
          onPress={() => handleVerification(accountVerification)}>
```

2021-12-30 02:35 UTC, datduong56 requested changes

2021-12-30 02:35 UTC, datduong56 commented on src/redux/slices/auth.ts
> +
Ông lên dùng một biến enum ở đây cho dễ nhận biết hơn

```suggestion
export enum LoginStatus {
      Success = 'Login Success',
      Failed = 'Login Failed',
      None = 'None',
},

export enum LogoutStatus {
      Success = 'Logout Success',
      Failed = 'Logout Failed',
      None = 'None',
},
```

2021-12-30 02:35 UTC, datduong56 commented on src/redux/slices/auth.ts
> +      if (action.payload.login === 'login success') {
```suggestion
      if (action.payload.login === LoginStatus.Success) {
```

2021-12-30 02:35 UTC, datduong56 commented on src/redux/slices/auth.ts
> +      if (action.payload === 'user logout') {
```suggestion
      if (action.payload === LogoutStatus.Success) {
```

2021-12-30 02:35 UTC, datduong56 commented on src/screens/account.tsx
> +        onPress: () => dispatch(authActions.onLogout('user logout')),
```suggestion
        onPress: () => dispatch(authActions.onLogout(LogoutStatus.Success)),
```

2021-12-30 02:35 UTC, datduong56 commented on src/screens/account.tsx
> +      { text: 'Cancel' },
```suggestion
      { text: 'Cancel', onPress: () => dispatch(authActions.onLogout(LogoutStatus.None)), },
```

2021-12-30 02:35 UTC, datduong56 commented on src/screens/account.tsx
> +      </Text>
```suggestion
      <Text style={{ textTransfom: "capitalize" }}>
        {`Name: ${userProfile?.name?.firstname} ${userProfile?.name?.lastname}`}
      </Text>
```

2021-12-30 04:14 UTC, Conlilo commented on src/redux/slices/auth.ts
> +
tôi có dùng api hẳn hoi đâu mà làm rõ đến mức đó

2021-12-30 04:14 UTC, ngxhuyhoang commented on src/redux/slices/auth.ts
> +
Ông chat mà cũng ngọng thì chịu

2021-12-30 04:14 UTC, ngxhuyhoang commented on src/redux/slices/cart.ts
> +    console.log('ahhaha');
```suggestion
```

2021-12-30 04:17 UTC, ngxhuyhoang commented on src/screens/account.tsx
> +  const capitalize = (s: any) => {
```suggestion
  const capitalize = (s: string) => {
```

2021-12-30 04:22 UTC, ngxhuyhoang commented on src/screens/login.tsx
> +        [{ text: 'Congfirm' }],
```suggestion
        [{ text: 'Confirm' }],
```

2021-12-30 04:23 UTC, ngxhuyhoang commented on src/screens/login.tsx
> +        </TouchableOpacity> */}
Chỗ này không dùng nữa thì xóa đi

2021-12-30 04:23 UTC, ngxhuyhoang commented on src/screens/login.tsx
> +  // },
Chỗ này không dùng nữa thì xóa đi

2021-12-30 08:32 UTC, ngxhuyhoang approved these changes

2021-12-30 08:32 UTC, merged